config/routes.rb
Rails.application.routes.draw do
  resources :builds

end

app/models/build.rb
class Build < ActiveRecord::Base
  has_many :special_stats, dependent: :destroy
  has_many :perks, dependent: :destroy

  accepts_nested_attributes_for :special_stats, :perks

  before_create :initialize_stats

  protected
  def initialize_stats
    self.name = "Lone Wanderer"
    self.description = "Just another wastelander"
    set_special
    set_perks
  end

  def set_special
    all_specials = SpecialStatType.all
    all_specials.each do |special|
      stat = SpecialStat.new(special_stat_type_id: special.id, level: 1)
      special_stats << stat
    end
  end

  def set_perks
    perk_types = PerkType.all
    perk_types.each do |perk_type|
      perks << Perk.new(current_rank: 0, perk_type: perk_type)
    end
  end
end

app/models/perk.rb
class Perk < ActiveRecord::Base
  belongs_to :perk_type
  belongs_to :build
  validate :current_rank_not_greater_than_total_ranks

  delegate :name,         to: :perk_type
  delegate :description,  to: :perk_type

  private
  def current_rank_not_greater_than_total_ranks
    if current_rank > perk_type.total_ranks
      errors.add(:current_rank, "can't be greater than #{perk_type.total_ranks}")
    end
  end
end

app/models/perk_type.rb
class PerkType < ActiveRecord::Base
  has_many :perks
end

app/models/special_stat.rb
class SpecialStat < ActiveRecord::Base
  belongs_to :special_stat_type
  belongs_to :build

  validates :level, numericality: {less_than_or_equal_to: 10, greater_than: 0}

  delegate :name,         to: :special_stat_type
  delegate :description,  to: :special_stat_type
end

app/models/special_stat_type.rb
class SpecialStatType < ActiveRecord::Base
  has_many :special_stats
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  before_action :set_build, only: [:show, :edit, :update, :destroy]

  # GET /builds
  def index
    @builds = Build.all
  end

  # GET /builds/1
  def show
    @perk_specials = SpecialStatType.all
  end

  # GET /builds/new
  # def new
  #   @build = Build.create
  #
  #   redirect_to edit_build_path(@build)
  # end

  # GET /builds/1/edit
  def edit
  end

  # POST /builds
  def create
    @build = Build.new

    if @build.save
      redirect_to @build, notice: 'Build was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /builds/1
  def update
    if @build.update(build_params)
      redirect_to @build, notice: 'Build was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /builds/1
  def destroy
    @build.destroy
    redirect_to builds_url, notice: 'Build was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_build
      @build = Build.includes([{perks: :perk_type}, {special_stats: :special_stat_type}]).find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def build_params
      params.require(:build).permit(:name, :description, perks_attributes: [:id, :current_rank],
          special_stats_attributes: [:level, :id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/builds_helper.rb
module BuildsHelper
end

app/views/builds/_form.html.erb
<%= form_for(@build) do |f| %>
  <% if @build.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@build.errors.count, "error") %> prohibited this build from being saved:</h2>

      <ul>
      <% @build.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/builds/edit.html.erb
<h1>Editing Build</h1>

<%= render 'form' %>

<%= link_to 'Show', @build %> |
<%= link_to 'Back', builds_path %>

app/views/builds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Builds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @builds.each do |build| %>
      <tr>
        <td><%= build.name %></td>
        <td><%= build.description %></td>
        <td><%= link_to 'Show', build %></td>
        <td><%= link_to 'Edit', edit_build_path(build) %></td>
        <td><%= link_to 'Destroy', build, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Build', builds_path, method: 'post' %>

app/views/builds/new.html.erb
<h1>New Build</h1>

<%= render 'form' %>

<%= link_to 'Back', builds_path %>

app/views/builds/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row build-title">
  <div class=col-md-12><h2><%= @build.name %> - <%= @build.description %> <%= link_to "", edit_build_path(@build), class: " change-name glyphicon glyphicon-pencil" %></h2></div>
</div>

<div class="prompt">
  <span class="points-remaining">21</span> starting SPECIAL points remaining.
</div>

<div class="special">
  <% @build.special_stats.each do |special| %>
    <div class="row special-stats">
      <div class="col-md-2 special-name"><%= special.name %></div>
      <div class="col-md-2">
        <span class="glyphicon glyphicon-triangle-left decrease-special"></span>
        <span class="special-level"><%= special.level %></span>
        <span class="glyphicon glyphicon-triangle-right increase-special"></span>
      </div>
    </div>
  <% end %>
</div>

<div class="prompt">
  On each level up, you can invest in the perks below, or add one to a SPECIAL stat above.
  You have spent <span class="num-perks">0</span> perks.
</div>

<div class="row seven-cols perks">
  <% @perk_specials.each do |perk_special| %>
    <div class="col-md-1">
    <% @build.perks.each do |perk| %>
      <% if perk.perk_type.special_stat_type_id == perk_special.id %>
        <span class="perk-name" data-toggle="popover" title="<%= perk.name %>" data-content="<%= perk.description%>">
          <%= perk.name %>
        </span>
        <br />
        <span class="glyphicon glyphicon-triangle-left decrease-perk"></span>
        <span class="perk-level"><%= perk.current_rank %>/<%= perk.perk_type.total_ranks%></span>
        <span class="glyphicon glyphicon-triangle-right increase-perk"></span>
        <br />
      <% end %>
    <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>F4BuildPlanner</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>